version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass@#word
      POSTGRES_DB: casa-os-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    mem_limit: 512m
    memswap_limit: 512m
    networks:
      - database

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: pass@#word
      DB_NAME: casa-os-postgres
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      LISTEN_PORT: 6432
      AUTH_TYPE: md5
    ports:
      - '6432:6432'
    depends_on:
      - postgres
    networks:
      - database
    volumes:
      - ./userlist.txt:/etc/pgbouncer/userlist.txt

networks:
  database:
    driver: bridge

volumes:
  postgres_data:
    driver: local
