version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass@#word
      POSTGRES_DB: casa-os-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m
    memswap_limit: 512m

volumes:
  postgres_data:
    driver: local
